# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default=None, upload_to='', verbose_name='头像'),
        ),
    ]
